# Data Preprocessing

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("churn_prediction.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15930 entries, 0 to 15929
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   customer_id                     15930 non-null  int64
 1   vintage                         15930 non-null  int64
 2   age                             15930 non-null  int64
 3   gender                          15642 non-null  object
 4   dependents                      14582 non-null  float64
 5   occupation                      15883 non-null  object
 6   city                            15470 non-null  float64
 7   customer_nw_category            15930 non-null  int64
 8   branch_code                     15930 non-null  int64
 9   current_balance                 15930 non-null  float64
 10  previous_month_end_balance      15930 non-null  float64
 11  average_monthly_balance_prevQ   15930 non-null  float64
 12  average_monthly_balance_prevQ2  15930 non-null  float64
 13  current_month_credit            15930 non-null  float64
 14  previous_month_credit           15930 non-null  float64
 15  current_month_debit             15930 non-null  float64
 16  previous_month_debit            15929 non-null  float64
 17  current_month_balance           15929 non-null  float64
 18  previous_month_balance          15929 non-null  float64
 19  last_transaction                15929 non-null  object
 20  churn                           15929 non-null  float64
dtypes: float64(13), int64(5), object(3)
memory usage: 2.6+ MB

## Variable Identification and Typecasting

In [188]:
# A closer look at the data types present in the data
df.dtypes

customer_id                         int64
vintage                             int64
age                                 int64
gender                             object
dependents                        float64
occupation                         object
city                              float64
customer_nw_category                int64
branch_code                         int64
current_balance                   float64
previous_month_end_balance        float64
average_monthly_balance_prevQ     float64
average_monthly_balance_prevQ2    float64
current_month_credit              float64
previous_month_credit             float64
current_month_debit               float64
previous_month_debit              float64
current_month_balance             float64
previous_month_balance            float64
last_transaction                   object
churn                             float64
dtype: object

There are a lot of variables visible at one, so let's narrow this down by looking **at one datatype at once**. We will start with int

### Integer Data Type

In [4]:
# Identifying variables with integer datatype
df.dtypes[df.dtypes == 'int64']

customer_id             int64
vintage                 int64
age                     int64
customer_nw_category    int64
branch_code             int64
dtype: object

Summary:

*    **Customer id** are a unique number assigned to customers. It is **Okay to consider this as an Integer**. This variable would not considered for our analysis.

*    **branch code** again represents different branches, therefore it should be **convereted to category**.

*    **Age** and **Vintage** are also numbers and hence we are okay with them as integers.

*    **customer_networth_category** is supposed to be an ordinal category, **should be converted to category**.

*    **churn** : 1 represents the churn and 0 represents not churn. However, there is no comparison between these two categories. This **needs to be converted to category datatype**.

In [190]:
df.describe()

,customer_id,vintage,age,dependents,city,customer_nw_category,branch_code,current_balance,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,churn
count,15930.000000,15930.000000,15930.000000,14582.000000,15470.000000,15930.000000,15930.000000,1.593000e+04,1.593000e+04,1.593000e+04,1.593000e+04,1.593000e+04,1.593000e+04,1.593000e+04,1.592900e+04,1.592900e+04,1.592900e+04,15929.00000
mean,8498.085625,2392.437728,48.174576,0.356741,795.157207,2.221846,927.797928,7.271421e+03,7.386992e+03,7.433499e+03,7.183789e+03,3.279202e+03,3.419490e+03,3.498199e+03,3.466232e+03,7.362582e+03,7.438765e+03,0.18752
std,4910.076657,272.486481,17.865815,1.086172,430.395665,0.662057,937.402995,5.051191e+04,4.944242e+04,4.893540e+04,5.528574e+04,3.124726e+04,3.541268e+04,2.825728e+04,2.772081e+04,4.933807e+04,4.973615e+04,0.39034
min,1.000000,438.000000,1.000000,0.000000,0.000000,1.000000,1.000000,-5.503960e+03,-2.998640e+03,1.428690e+03,-1.650610e+04,1.000000e-02,1.000000e-02,1.000000e-02,1.000000e-02,-3.374180e+03,-3.060130e+03,0.00000
25%,4245.250000,2260.000000,35.000000,0.000000,409.000000,2.000000,176.000000,1.776387e+03,1.908638e+03,2.168155e+03,1.822055e+03,3.100000e-01,3.300000e-01,4.100000e-01,4.100000e-01,1.988660e+03,2.077040e+03,0.00000
50%,8485.500000,2454.000000,46.000000,0.000000,834.000000,2.000000,578.000000,3.276645e+03,3.381180e+03,3.520035e+03,3.373785e+03,6.100000e-01,6.400000e-01,9.440000e+01,1.124800e+02,3.445410e+03,3.450510e+03,0.00000
75%,12752.750000,2593.000000,60.000000,0.000000,1096.000000,3.000000,1437.000000,6.624458e+03,6.686012e+03,6.676240e+03,6.532695e+03,7.075825e+02,7.718425e+02,1.393230e+03,1.357730e+03,6.658490e+03,6.679810e+03,0.00000
max,16997.000000,2776.000000,90.000000,52.000000,1648.000000,3.000000,4753.000000,5.905904e+06,5.740439e+06,5.700290e+06,5.010170e+06,1.764286e+06,2.361808e+06,1.764286e+06,1.414168e+06,5.778185e+06,5.720144e+06,1.00000

In [5]:
# converting churn to category
df['churn'] = df['churn'].astype('category')
df['branch_code'] = df['branch_code'].astype('category')
df['customer_nw_category'] = df['customer_nw_category'].astype('category')
df.dtypes[df.dtypes == 'int64']

customer_id    int64
vintage        int64
age            int64
dtype: object

In [6]:
df.describe()

,customer_id,vintage,age,dependents,city,current_balance,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance
count,15930.000000,15930.000000,15930.000000,14582.000000,15470.000000,1.593000e+04,1.593000e+04,1.593000e+04,1.593000e+04,1.593000e+04,1.593000e+04,1.593000e+04,1.592900e+04,1.592900e+04,1.592900e+04
mean,8498.085625,2392.437728,48.174576,0.356741,795.157207,7.271421e+03,7.386992e+03,7.433499e+03,7.183789e+03,3.279202e+03,3.419490e+03,3.498199e+03,3.466232e+03,7.362582e+03,7.438765e+03
std,4910.076657,272.486481,17.865815,1.086172,430.395665,5.051191e+04,4.944242e+04,4.893540e+04,5.528574e+04,3.124726e+04,3.541268e+04,2.825728e+04,2.772081e+04,4.933807e+04,4.973615e+04
min,1.000000,438.000000,1.000000,0.000000,0.000000,-5.503960e+03,-2.998640e+03,1.428690e+03,-1.650610e+04,1.000000e-02,1.000000e-02,1.000000e-02,1.000000e-02,-3.374180e+03,-3.060130e+03
25%,4245.250000,2260.000000,35.000000,0.000000,409.000000,1.776387e+03,1.908638e+03,2.168155e+03,1.822055e+03,3.100000e-01,3.300000e-01,4.100000e-01,4.100000e-01,1.988660e+03,2.077040e+03
50%,8485.500000,2454.000000,46.000000,0.000000,834.000000,3.276645e+03,3.381180e+03,3.520035e+03,3.373785e+03,6.100000e-01,6.400000e-01,9.440000e+01,1.124800e+02,3.445410e+03,3.450510e+03
75%,12752.750000,2593.000000,60.000000,0.000000,1096.000000,6.624458e+03,6.686012e+03,6.676240e+03,6.532695e+03,7.075825e+02,7.718425e+02,1.393230e+03,1.357730e+03,6.658490e+03,6.679810e+03
max,16997.000000,2776.000000,90.000000,52.000000,1648.000000,5.905904e+06,5.740439e+06,5.700290e+06,5.010170e+06,1.764286e+06,2.361808e+06,1.764286e+06,1.414168e+06,5.778185e+06,5.720144e+06

### Float Data Type

In [7]:
# Identifying variables with float datatype
df.dtypes[df.dtypes == 'float64']

dependents                        float64
city                              float64
current_balance                   float64
previous_month_end_balance        float64
average_monthly_balance_prevQ     float64
average_monthly_balance_prevQ2    float64
current_month_credit              float64
previous_month_credit             float64
current_month_debit               float64
previous_month_debit              float64
current_month_balance             float64
previous_month_balance            float64
dtype: object

Summary:

*    **dependents** is expected to be a whole number. **Should be changed to integer type**

*    **city** variable is also a unique code of a city represented by some interger number. **Should be converted to Category type**

*    Rest of the variables like **credit, balance and debit** are best represented by the float variables.

In [8]:
# converting "dependents" and "city" to their respective types
df['dependents'] = df['dependents'].astype('Int64')
df['city'] = df['city'].astype('category')

# checking
df[['dependents','city']].dtypes

dependents       Int64
city          category
dtype: object

### Object Data Type

In [195]:
df.dtypes

customer_id                          int64
vintage                              int64
age                                  int64
gender                              object
dependents                           Int64
occupation                          object
city                              category
customer_nw_category              category
branch_code                       category
current_balance                    float64
previous_month_end_balance         float64
average_monthly_balance_prevQ      float64
average_monthly_balance_prevQ2     float64
current_month_credit               float64
previous_month_credit              float64
current_month_debit                float64
previous_month_debit               float64
current_month_balance              float64
previous_month_balance             float64
last_transaction                    object
churn                             category
dtype: object

*    **variables like 'gender', 'occupation' and 'last_transaction' are of type object**. This means that **Pandas was not able to recognise the datatype** of these three variables.

In [9]:
# Manually checking object types
df[['gender','occupation','last_transaction']].head(7)

   gender     occupation last_transaction
0    Male  self_employed       2019-05-21
1    Male  self_employed       2019-11-01
2    Male       salaried              NaT
3     NaN  self_employed       2019-08-06
4    Male  self_employed       2019-11-03
5  Female  self_employed       2019-11-01
6    Male        retired       2019-09-24

*    **gender** and **occupation** variables **belong to categorical data types**.
*    **last_transaction** should be a  **datetime variable**.

In [10]:
# typecasting "gender" and "occupation" to category type
df['gender'] = df['gender'].astype('category')
df['occupation'] = df['occupation'].astype('category')

# checking
df[['gender','occupation']].dtypes

gender        category
occupation    category
dtype: object

# Missing values

In [11]:
df.isna().sum()  # list of all the columns having missing vlaues & the number f missing values

customer_id                          0
vintage                              0
age                                  0
gender                             288
dependents                        1348
occupation                          47
city                               460
customer_nw_category                 0
branch_code                          0
current_balance                      0
previous_month_end_balance           0
average_monthly_balance_prevQ        0
average_monthly_balance_prevQ2       0
current_month_credit                 0
previous_month_credit                0
current_month_debit                  0
previous_month_debit                 1
current_month_balance                1
previous_month_balance               1
last_transaction                     1
churn                                1
dtype: int64

In [13]:
#df['gender'].fillna(value=df['gender'].mode()[0], inplace=True)
df.fillna({'gender': df['gender'].mode()[0]}, inplace=True)

In [14]:
df['gender'].isna().sum()   # there no more missing vlues

0

In [16]:

df.fillna({'occupation': df['occupation'].mode()[0]}, inplace=True)

In [202]:
df['occupation'].isna().sum()

0

In [17]:
df['city'].value_counts()

city
1020.0    1949
1096.0    1136
409.0      762
146.0      691
834.0      641
          ...
911.0        1
916.0        1
919.0        1
921.0        1
832.0        1
Name: count, Length: 1287, dtype: int64

In [18]:
df["city"]

0         187.0
1           NaN
2         146.0
3        1020.0
4        1494.0
          ...
15925     409.0
15926    1020.0
15927     557.0
15928    1540.0
15929    1096.0
Name: city, Length: 15930, dtype: category
Categories (1287, float64): [0.0, 1.0, 2.0, 3.0, ..., 1645.0, 1646.0, 1647.0, 1648.0]

In [19]:
df['dependents'].isna().sum()

1348

In [21]:
#gp = df.groupby(df['gender'])
#gp['dependents'].mean().round()
gp = df.groupby(df['gender'], observed=True)

In [23]:
def impute_nan_dependents(cols):
    gender = cols.iloc[0]
    dep = cols.iloc[1]
        
    if pd.isnull(dep):
        return 1 if gender == 'Male' else 0
    else:
        return dep

df['dependents'] = df[['gender', 'dependents']].apply(impute_nan_dependents, axis=1)

In [24]:
df[['gender', 'dependents']].head()

  gender  dependents
0   Male           0
1   Male           0
2   Male           0
3   Male           1
4   Male           2

In [25]:
df.isna().sum()

customer_id                         0
vintage                             0
age                                 0
gender                              0
dependents                          0
occupation                          0
city                              460
customer_nw_category                0
branch_code                         0
current_balance                     0
previous_month_end_balance          0
average_monthly_balance_prevQ       0
average_monthly_balance_prevQ2      0
current_month_credit                0
previous_month_credit               0
current_month_debit                 0
previous_month_debit                1
current_month_balance               1
previous_month_balance              1
last_transaction                    1
churn                               1
dtype: int64

In [26]:
df.dropna(axis=0, inplace=True)  # drop those col which have missing values

In [27]:
from sklearn.preprocessing import OneHotEncoder

In [28]:
ohe = OneHotEncoder(min_frequency=0.01, max_categories=10, sparse_output=False).set_output(transform='pandas')

In [29]:
ohe.fit(df[['city']])

OneHotEncoder(max_categories=10, min_frequency=0.01, sparse_output=False)

In [30]:
ohe.transform(df[['city']]).shape

(15469, 10)

In [31]:
ohe_city = ohe.transform(df[['city']])

In [32]:
df.shape

(15469, 21)

In [33]:
df = pd.concat([df, ohe_city], axis=1)

In [34]:
df.shape

(15469, 31)

In [35]:
df.columns

Index(['customer_id', 'vintage', 'age', 'gender', 'dependents', 'occupation',
       'city', 'customer_nw_category', 'branch_code', 'current_balance',
       'previous_month_end_balance', 'average_monthly_balance_prevQ',
       'average_monthly_balance_prevQ2', 'current_month_credit',
       'previous_month_credit', 'current_month_debit', 'previous_month_debit',
       'current_month_balance', 'previous_month_balance', 'last_transaction',
       'churn', 'city_15.0', 'city_146.0', 'city_334.0', 'city_409.0',
       'city_623.0', 'city_834.0', 'city_1020.0', 'city_1096.0', 'city_1232.0',
       'city_infrequent_sklearn'],
      dtype='object')

In [36]:
df.drop(['customer_id', "city", "branch_code"], axis=1, inplace=True)  # dropping the customer_id col

In [37]:
df.head()

,vintage,age,gender,dependents,occupation,customer_nw_category,current_balance,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,...,city_15.0,city_146.0,city_334.0,city_409.0,city_623.0,city_834.0,city_1020.0,city_1096.0,city_1232.0,city_infrequent_sklearn
0,2401,66,Male,0,self_employed,2,1458.71,1458.71,1458.71,1449.07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2494,31,Male,0,salaried,2,3913.16,5815.29,4910.17,2815.94,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2629,90,Male,1,self_employed,2,2291.91,2291.91,2084.54,1006.54,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1879,42,Male,2,self_employed,3,927.72,1401.72,1643.31,1871.12,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,2223,42,Female,0,self_employed,2,15202.20,16059.34,15211.29,13798.82,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [38]:
df.dropna(axis=1, inplace=True)  # drop those col which have missing values

In [39]:
df.isna().sum()

vintage                           0
age                               0
gender                            0
dependents                        0
occupation                        0
customer_nw_category              0
current_balance                   0
previous_month_end_balance        0
average_monthly_balance_prevQ     0
average_monthly_balance_prevQ2    0
current_month_credit              0
previous_month_credit             0
current_month_debit               0
previous_month_debit              0
current_month_balance             0
previous_month_balance            0
last_transaction                  0
churn                             0
city_15.0                         0
city_146.0                        0
city_334.0                        0
city_409.0                        0
city_623.0                        0
city_834.0                        0
city_1020.0                       0
city_1096.0                       0
city_1232.0                       0
city_infrequent_sklearn           0
dtype: int64

In [40]:
df['gender'] = df['gender'].map({'Male':0, 'Female':1})  # Label Encoding the gender col. This can also be One-hot encoded

In [41]:
pd.get_dummies(df['occupation'], drop_first=True, dtype="int")   # OHE the occupation

       retired  salaried  self_employed  student
0            0         0              1        0
2            0         1              0        0
3            0         0              1        0
4            0         0              1        0
5            0         0              1        0
...        ...       ...            ...      ...
15924        0         1              0        0
15925        0         0              1        0
15926        0         1              0        0
15927        0         0              1        0
15928        0         0              1        0

[15469 rows x 4 columns]

In [43]:
nominal_cols = ['occupation', 'customer_nw_category'] # Selecting out the columns for OHE    #  'city',

In [44]:
df = pd.get_dummies(df, columns=nominal_cols, drop_first=True, dtype="int") # One-Hot encoding the Nominal columns

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15469 entries, 0 to 15928
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   vintage                         15469 non-null  int64
 1   age                             15469 non-null  int64
 2   gender                          15469 non-null  category
 3   dependents                      15469 non-null  int64
 4   current_balance                 15469 non-null  float64
 5   previous_month_end_balance      15469 non-null  float64
 6   average_monthly_balance_prevQ   15469 non-null  float64
 7   average_monthly_balance_prevQ2  15469 non-null  float64
 8   current_month_credit            15469 non-null  float64
 9   previous_month_credit           15469 non-null  float64
 10  current_month_debit             15469 non-null  float64
 11  previous_month_debit            15469 non-null  float64
 12  current_month_balance           15469 non-null  float64
 13  previous_month_balance          15469 non-null  float64
 14  last_transaction                15469 non-null  object
 15  churn                           15469 non-null  category
 16  city_15.0                       15469 non-null  float64
 17  city_146.0                      15469 non-null  float64
 18  city_334.0                      15469 non-null  float64
 19  city_409.0                      15469 non-null  float64
 20  city_623.0                      15469 non-null  float64
 21  city_834.0                      15469 non-null  float64
 22  city_1020.0                     15469 non-null  float64
 23  city_1096.0                     15469 non-null  float64
 24  city_1232.0                     15469 non-null  float64
 25  city_infrequent_sklearn         15469 non-null  float64
 26  occupation_retired              15469 non-null  int32
 27  occupation_salaried             15469 non-null  int32
 28  occupation_self_employed        15469 non-null  int32
 29  occupation_student              15469 non-null  int32
 30  customer_nw_category_2          15469 non-null  int32
 31  customer_nw_category_3          15469 non-null  int32
dtypes: category(2), float64(20), int32(6), int64(3), object(1)
memory usage: 3.3+ MB

In [46]:
df.sample(10)

,vintage,age,gender,dependents,current_balance,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,...,city_1020.0,city_1096.0,city_1232.0,city_infrequent_sklearn,occupation_retired,occupation_salaried,occupation_self_employed,occupation_student,customer_nw_category_2,customer_nw_category_3
14822,1964,43,0,0,5935.77,4507.20,3104.91,326.03,1500.04,7142.90,...,0.0,0.0,0.0,1.0,0,0,1,0,0,1
3202,2349,41,0,1,5735.95,7164.52,5090.95,163.44,0.61,3572.04,...,0.0,0.0,0.0,1.0,0,0,1,0,1,0
2699,2556,35,0,0,15541.28,11762.48,8752.93,20510.34,4286.24,11429.10,...,0.0,0.0,0.0,1.0,0,0,1,0,1,0
5355,2328,47,0,2,21521.39,693.03,8761.53,1024.55,0.29,857.43,...,0.0,0.0,0.0,0.0,0,0,1,0,1,0
14225,2198,90,0,0,1180.53,2466.24,1937.72,1598.54,192.99,192.99,...,0.0,0.0,0.0,1.0,1,0,0,0,0,0
14799,2483,64,0,0,7931.87,87775.89,68170.40,107029.68,283196.17,15.21,...,1.0,0.0,0.0,0.0,0,0,1,0,1,0
6653,2547,26,0,0,1004.75,1681.49,1534.28,1133.42,464.60,414.11,...,0.0,0.0,0.0,0.0,0,0,1,0,0,1
10521,2615,36,1,0,2068.68,2068.68,2087.12,2055.58,0.04,428.61,...,0.0,0.0,0.0,1.0,0,0,1,0,0,1
9238,1851,90,1,0,6962.09,6676.37,6654.87,6226.04,0.20,0.20,...,0.0,1.0,0.0,0.0,0,0,1,0,1,0
12579,2486,55,0,2,3769.17,3708.20,2028.49,1463.50,0.57,1072.00,...,1.0,0.0,0.0,0.0,0,0,1,0,1,0

In [47]:
df.to_pickle("churn_prediction_cleaned.pkl")

,vintage,age,gender,dependents,current_balance,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,...,city_1020.0,city_1096.0,city_1232.0,city_infrequent_sklearn,occupation_retired,occupation_salaried,occupation_self_employed,occupation_student,customer_nw_category_2,customer_nw_category_3
9084,2467,90,0,0,20246.90,20246.90,20246.90,20065.47,0.44,0.44,...,1.0,0.0,0.0,0.0,0,0,1,0,0,0
10994,2179,32,1,0,10049.21,8683.88,7821.57,5031.51,0.31,5.46,...,0.0,0.0,0.0,1.0,0,1,0,0,0,1
2471,2369,43,0,2,1270.34,1648.72,1533.67,1257.87,214.46,214.46,...,0.0,0.0,0.0,0.0,0,0,1,0,0,1
13316,2564,39,1,0,2360.53,2360.53,2360.53,2410.45,0.24,0.24,...,0.0,0.0,0.0,0.0,0,0,1,0,1,0
7493,2575,49,0,0,4029.97,4071.06,4220.52,4298.49,0.60,0.60,...,1.0,0.0,0.0,0.0,0,0,1,0,1,0
7795,2274,65,0,0,1455.29,1539.15,1604.26,1958.60,0.27,0.27,...,0.0,0.0,0.0,1.0,1,0,0,0,1,0
15668,2483,42,0,0,4097.14,3292.69,3564.91,1531.19,1103.33,993.33,...,0.0,0.0,0.0,1.0,0,0,1,0,0,1
2535,2273,90,0,1,4915.53,5629.81,5590.01,5731.66,0.31,0.31,...,0.0,0.0,0.0,1.0,0,0,1,0,1,0
7721,2255,52,1,0,1950.96,2228.92,1835.95,1836.59,0.49,0.49,...,0.0,0.0,0.0,0.0,0,0,1,0,0,0
9450,2716,68,0,1,2122.45,8731.62,2976.55,3284.40,6143.13,5107.41,...,0.0,0.0,1.0,0.0,0,0,1,0,1,0